---
title: "Eliminating Racial Bias Relating to Violent Crimes in U.S. Communities using a Predictive Machine Learning Model"
author: "input our names here"
format: pdf
editor: visual
---

# Reading Libraries and Dataset

```{r}
# Add all applicable libraries
library(tidyverse)
library(ggplot2)
library(dplyr)
library(tidyr)
library(corrplot)

CrimeData <- read.csv("https://raw.githubusercontent.com/snehaprem03/StatProject/main/communities.data", header = TRUE, na.strings = "?")

#This reads the csv file, addresses the first row as a header, and then changes all the "?" values to NA in order to make it easier to change later
```

\-

# 1. Data Tidying and Manipulation

### 1.1 Understanding Our Data

```{r}
head(CrimeData) #first few rows
str(CrimeData) # structure of the data set
```

```{r}
summary(CrimeData) #summary statistics + distribution of each variable
```

```{r}
CrimeData %>% summarise_all(n_distinct) #number of unique values for each column of the data frame
```

### 1.2 Cleaning and Pre-Processing Data

```{r}
CrimeData %>% summarise_all(~ sum(is.na(.)))
# We can see that country, community, LemasSwornFT, LemasSwFTPerPop, LemasSwFTFieldOps, LemasSwFTFieldPerPop, LemasTotalReq, LemasTotReqPerPop, PolicReqPerOffic, PolicPerPo, RacialMatchCom, PctPolicWhite, PctPolicBlack, PctPolicHisp, PctPolicAsian, PctPolicMinor, OfficAssgnDrugUnits, NumKindsDrugsSeiz, PolicAveOTWorked, PolicCars, PolicOperBudg, LemasPctPolicOnPatr, LemasGangUnitDeploy, PolicBudgPerPop all have missing values (1675 for almost all but 1174 for the first two)

```

```{r}
# The LEMAS data seems to have a lot of missing values. About 1675/1994 or 84% of the LEMAS columns have missing data. So, the best way to handle this is probably to drop those columns


# Identify columns with more than 80% missing data
na_percent <- apply(is.na(CrimeData), 2, mean)
cols_to_drop <- names(na_percent[na_percent > 0.8])

# List Dropped Columns
cat("Dropped columns:", paste(cols_to_drop, collapse = ", "))

# Drop the columns with more than 80% missing data
CrimeData <- CrimeData[, !names(CrimeData) %in% cols_to_drop]



```

```{r}
# Dropping the County and Community columns"

CrimeData <- CrimeData[, !(names(CrimeData) %in% c("country", "community"))]

```

```{r}
# OtherPerCap also has one missing row. We can use the mean of the column to replace this NA value since it is the only one

mean_other_percap <- mean(CrimeData$OtherPerCap, na.rm = TRUE)
CrimeData$OtherPerCap[is.na(CrimeData$OtherPerCap)] <- mean_other_percap
```

```{r}
# Final Check for Any Missing Values
CrimeData %>% summarise_all(~ sum(is.na(.)))

```

# Variable Creation, Selection, and Manipulation

```{r}

```

\-

# Introductory Plots

```{r}

```

\-

# Exploratory Data Analysis

```{r}

```

\-
